---
name: Config Sync

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    uses: DevSecNinja/.github/.github/workflows/config-sync.yml@7a3e8e1475c658c60c23bedc7daf2e559bfe60b4 # v3.1.0
    permissions:
      contents: write
      pull-requests: write
